/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC721 } from "./ERC721";
export type { Fame } from "./Fame";
export type { Getter } from "./Getter";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { ERC721__factory } from "./factories/ERC721__factory";
export { Fame__factory } from "./factories/Fame__factory";
export { Getter__factory } from "./factories/Getter__factory";
